# Generated by Django 5.1.7 on 2025-04-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_alter_investment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='value_history',
            field=models.JSONField(default=list),
        ),
    ]
